// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhtaedzkfozrkndlonxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodGFlZHprZm96cmtuZGxvbnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTI2NjksImV4cCI6MjA2ODYyODY2OX0.nwfkvDGsdMg1qe-bJGT0Iqfw2U4fYGkaw4iiV_0Ho6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});